a = input('Digite algo: ')
print('O tipo primmitivo desse valor é ', type(a))
print('Só tem espaco?', a.isnumeric())
print('É um numero?', a.isalnum())
print('É alfabetico?', a.isalpha())
print('É alfanumerico', a.isalnum())
print('Esta em maiuscula', a.isupper())
print('Está em minuscula', a.islower())
print('Está capitalizada? ', a.istitle())